# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:   # 这里是用来指定哪个文件更改，才会触发的
      - 'start'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Docker
        run: |
          docker pull wlxu/telegrambot:2.1.0
          docker run -d --name arpt -e Api_hash=b32c2fc6a6c8bfcf1e538ea48ca3f463 -e Api_id=8295502 -e Aria2_secret=1989938139a -e Remote=yun -e Telegram_bot_api=1938142022:AAFw8qCKF3Oq48nS2yNo7-VM5KPXkQHrELw -e Telegram_user_id=1172538303 -e Upload=/TelegramBot -e Rclone_share=False -e Error_user_info="你没有使用权限" -p 8868:8868 wlxu/telegrambot:2.1.0

      # Runs a set of commands using the runners shell
      - name: Run Ding
        run: |
          chmod 777 ding
          ./ding -config=./ding.cfg -subdomain=TelegramBot 8868
